### ISSUE TITLE
[Bug] mediaSession在Android11设备上无法正常显示进度条

### ISSUE THREAD

**Issue by yyxida** [azuse/kikoeru-express#10]
mediaSession在Android11及以上设备上无法正常显示进度条，会一直显示100%的播放进度。
**版本**
1月5号的源码自行编译版本
**截图**
![image](https://user-images.githubusercontent.com/22792135/210704570-1911eb5c-22e3-4b93-a8ce-440f64331434.png)

**Comment by azuse** [comment]
能复现，暂停的时候时间又对了，我有空看看是怎么回事

**Comment by yyxida** [comment]
> 

大佬辛苦，新年快乐哈XD。

**Comment by azuse** [comment]
查了一下，是Chromium的BUG，最新的Chrome Canary我试这个bug已经修了
Referer:
https://stackoverflow.com/questions/65549393/mediapositionstate-shows-incorrect-currenttime
https://bugs.chromium.org/p/chromium/issues/detail?id=1167926
