### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by FANJANDA** [azuse/kikoeru-express#13]
![image](https://user-images.githubusercontent.com/18253492/235296481-6aec8981-790e-4f2c-af6a-05f1d6e1f241.png)
![image](https://user-images.githubusercontent.com/18253492/235296488-74c7e76d-d489-4419-af9e-ca5bda1e8d58.png)
有些没有办法dlsite无法搜索到的信息时可以转成去hvdb下载封面
![image](https://user-images.githubusercontent.com/18253492/235296543-2a9e5e62-1479-4ec0-8529-e0218dfeae86.png)
然后就是匹配到了6位的RJ号但是还是下载不了图片

**Comment by azuse** [comment]
看了下下载不到图片是因为汉化作品使用了非汉化作品的图片链接，
比如RJ01001197其实打开图片是使用的RJ337839的图片链接：
![image](https://user-images.githubusercontent.com/22174280/235428306-7e82defa-83f9-45de-929b-a4f69f0b8ea6.png)

kikoeru程序里直接通过RJ号拼接的图片链接，对于这种就没法识别。

比较简单的方法是要不你这个文件夹直接改名成RJ337839，应该可以正常获取日文meta信息，也不影响中文字幕。

**Comment by FANJANDA** [comment]
哦我那个挺多的就不改了，能用哈哈哈，就是还有些作品dlsite不售卖了就获取不到信息，能试试去hvdb获取的么



---Original---
From: ***@***.***&gt;
Date: Mon, May 1, 2023 16:23 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [azuse/kikoeru-express] [Bug]  (Issue #13)




 
看了下下载不到图片是因为汉化作品使用了非汉化作品的图片链接，
 比如RJ01001197其实打开图片是使用的RJ337839的图片链接：
 
 
kikoeru程序里直接通过RJ号拼接的图片链接，对于这种就没法识别。
 
比较简单的方法是要不你这个文件夹直接改名成RJ337839，应该可以正常获取日文meta信息，也不影响中文字幕。
